[package]
name = "sample-load"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.9.0"
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
clap = { version = "4.5.20", features = ["derive"] }

[dev-dependencies]
cargo-tarpaulin = "0.24.1"

